### ISSUE TITLE
--datepicker-container-border won't work

### ISSUE THREAD

**Issue by Set27** [svelte-plugins/datepicker#15]
```css
	:global(.datepicker[data-picker-theme='custom-datepicker']) {
		--datepicker-container-position: relative;
		/* --datepicker-container-width: max-width; */
		--datepicker-calendar-width: 375px;

		--datepicker-state-active: white;
		--datepicker-calendar-header-text-color: #black;
		--datepicker-calendar-day-color: #white;
		--datepicker-calendar-range-selected-background: #111;

		--datepicker-border-color: #111;

		--datepicker-container-border: 100px solid #111;
	}
```
![image](https://github.com/svelte-plugins/datepicker/assets/49077110/42dc3d94-a115-4469-8055-46d0c335b5f7)
